project:
  type: website

website:
  title: "Spring 2024 Bayesian Learning Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources

execute:
  freeze: auto
  
format:
  html:
    theme: 
      - sandstone #feel free to change to a different one https://bootswatch.com/
      - custom.scss
    css: https://use.typekit.net/emv3zbo.css #proxima-nova font
    toc: true
    
editor: 
  markdown:
    wrap: sentence
    canonical: true
