---
title: "Home"
---

Welcome to the website!

## Group objectives

-   Become experts in Bayesian statistics in a semester!
    Or, at least, absorb the **philosophy** and **conceptual underpinnings** of a Bayesian approach, and learn to **build and interpret** Bayesian models using **modern software packages**.

-   Support each other in this quest.
    Collectively we have a diversity of research interests, backgrounds in statistics and programming, and objectives for the semester.
    We will share our knowledge and our curiousity, and we will welcome questions, experiments, and intellectual risk-taking.
    We will collectively commit to maintaining a safe and welcoming environment for all (see the Code of Conduct, below).

## Learning group structure

-   Our objective is to provide structure and support for each other as we work through the *Statistical Rethinking* material and translate the concepts and tools we learn to our own work.

-   Between sessions, we will all read the current book chapter and/or watch the current video lectures.
    No need to both read and watch - we suggest picking your favorite modality and setting aside an hour or two in the "off week" between meetings to absorb the content.

-   In-session, we'll have a quick discussion reminding ourselves of the content, and then spend most of our time helping each other work through examples and use cases from your own work (if you have them).

-   We will encourage you to keep a digital notebook of your progress as a GitHub repository that you can refer back to later.
    We'll also curate resources as a group for future reference (and in case anyone misses a session and wants to catch up).

-   The structure and format of this learning group is ultimately what we make it!
    Suggestions and meta-brainstorming are welcome.

## Code of Conduct

> Our group's mission is to enable scientists.
> This means treating people with respect and responding in a polite and helpful way.
>
> Our group is committed to ensuring a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, or religion.
>
> Examples of unacceptable behavior by members, collaborators, and contributors include the use of sexual language or imagery, derogatory comments or personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct.

Read our full [code of conduct](https://osf.io/tzmhp/wiki/Code%20of%20Conduct/) and please report any violations or concerns to the course instructors or to Kristina Riemer ([kristinariemer\@arizona.edu](mailto:kristinariemer@arizona.edu)).

## Schedule

+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| Date                                             | Asynchronous content                                                                                                                            | In-session                                                                                                                                                                           | Leader          |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | (we suggest reading OR watching)                                                                                                                |                                                                                                                                                                                      |                 |
+==================================================+=================================================================================================================================================+======================================================================================================================================================================================+=================+
| 1/19/2024                                        | -   Ch. 1 The Golem of Prague                                                                                                                   | -   Introductions                                                                                                                                                                    | Jessica, Renata |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Lecture 1: [Science before statistics](https://www.youtube.com/watch?v=FdnMWdICdRs&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=1)         | -   Group setup and format                                                                                                                                                           |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Software setup                                                                                                                                                                   |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Discuss the drawing of owls                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 2/2/2024                                         | -   Ch. 2 Small Worlds and Large Worlds                                                                                                         | -   Code up Garden of Forking Data example                                                                                                                                           | Jessica, Renata |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
| **Time change: Meet from 11-1 instead of 12-2!** | -   Ch. 3 Sampling the Imaginary                                                                                                                | -   [Challenge problems here!](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week01.pdf)                                                                     |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Lecture 2: [The Garden of Forking Data](https://www.youtube.com/watch?v=R1vcdhPBlXA&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=2)        | -   Exercises in brms book [sections 2](https://bookdown.org/content/4857/small-worlds-and-large-worlds.html) and [3](https://bookdown.org/content/4857/sampling-the-imaginary.html) |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 2/16/2024                                        | -   Ch. 4 Linear Models                                                                                                                         | -   Challenge problems from McElreath's course [here](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week02.pdf)                                              |                 |
|                                                  |                                                                                                                                                 | -   [Exercises in brms book](https://bookdown.org/content/4857/geocentric-models.html)                                                                                               |                 |
|                                                  | -   Lecture 3: [Geocentric Models](https://www.youtube.com/watch?v=tNOu-SEacNU) (skip to 19:00 if you are familiar with Gaussian distributions) | -   Check pacing and set rest of schedule                                                                                                                                            |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Lecture 4: [Lines and Curves](https://www.youtube.com/watch?v=F0N4b7K_iYQ&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=4)                  |                                                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 3/1/2024                                         | -   Ch. 4 in 2020 edition                                                                                                                       | -   Review Chapter 4                                                                                                                                                                 |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |     -   Esp. section 4.5.2 Splines                                                                                                              | -   Problems on splines and building linear models                                                                                                                                   |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Demo (Jessica)                                                                                                                                                                   |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 3/15/2024                                        | -   Ch. 5 Many Variables and Spurious Waffles                                                                                                   | -   Ch. 5 Problems TBD                                                                                                                                                               |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Demo (Val)                                                                                                                                                                       |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 3/29/2024                                        | -   Ch. 6 The Haunted DAG and Causal Terror                                                                                                     | -   Ch 6 Problems TBD                                                                                                                                                                |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 4/12/2024                                        | -   Ch. 7 Ulysses' Compass                                                                                                                      | -   Ch. 7-8 Problems TBD                                                                                                                                                             |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Ch. 8 Conditional Manatees                                                                                                                  |                                                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 4/26/2024                                        | -   Ch. 9 MCMC                                                                                                                                  | -   Ch. 9 Problems                                                                                                                                                                   |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Wrap-up and Planning                                                                                                                                                             |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
