---
title: "Spring 2024 Schedule"
---

## Notes

[See the group HackMD for notes from the Spring series.](https://hackmd.io/z9Or6dTqRuKKkNHDeDM1cw?both=)

## Schedule

+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| Date                                             | Asynchronous content                                                                                                                            | In-session                                                                                                                                                                           | Leader          |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | (we suggest reading OR watching)                                                                                                                |                                                                                                                                                                                      |                 |
+==================================================+=================================================================================================================================================+======================================================================================================================================================================================+=================+
| 1/19/2024                                        | -   Ch. 1 The Golem of Prague                                                                                                                   | -   Introductions                                                                                                                                                                    | Jessica, Renata |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Lecture 1: [Science before statistics](https://www.youtube.com/watch?v=FdnMWdICdRs&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=1)         | -   Group setup and format                                                                                                                                                           |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Software setup                                                                                                                                                                   |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Discuss the drawing of owls                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 2/2/2024                                         | -   Ch. 2 Small Worlds and Large Worlds                                                                                                         | -   Code up Garden of Forking Data example                                                                                                                                           | Jessica, Renata |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
| **Time change: Meet from 11-1 instead of 12-2!** | -   Ch. 3 Sampling the Imaginary                                                                                                                | -   [Challenge problems here!](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week01.pdf)                                                                     |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Lecture 2: [The Garden of Forking Data](https://www.youtube.com/watch?v=R1vcdhPBlXA&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=2)        | -   Exercises in brms book [sections 2](https://bookdown.org/content/4857/small-worlds-and-large-worlds.html) and [3](https://bookdown.org/content/4857/sampling-the-imaginary.html) |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 2/16/2024                                        | -   Ch. 4 Linear Models                                                                                                                         | -   Challenge problems from McElreath's course [here](https://github.com/rmcelreath/stat_rethinking_2023/blob/main/homework/week02.pdf)                                              |                 |
|                                                  |                                                                                                                                                 | -   [Exercises in brms book](https://bookdown.org/content/4857/geocentric-models.html)                                                                                               |                 |
|                                                  | -   Lecture 3: [Geocentric Models](https://www.youtube.com/watch?v=tNOu-SEacNU) (skip to 19:00 if you are familiar with Gaussian distributions) | -   Check pacing and set rest of schedule                                                                                                                                            |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Lecture 4: [Lines and Curves](https://www.youtube.com/watch?v=F0N4b7K_iYQ&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=4)                  |                                                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 3/1/2024                                         | -   N/A                                                                                                                                         | -   Demo (Jessica)                                                                                                                                                                   |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 3/15/2024                                        | -   Continue Ch 4.                                                                                                                              | -   Ch. 4                                                                                                                                                                            |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Demo (Val)                                                                                                                                                                       |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 3/29/2024                                        | -   Ch. 5 Many Variables and Spurious Waffles                                                                                                   | -   Ch 6 Problems TBD                                                                                                                                                                |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | <!-- -->                                                                                                                                        |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Ch. 6 The Haunted DAG and Causal Terror                                                                                                     |                                                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 4/12/2024                                        | -   Ch. 7 Ulysses' Compass                                                                                                                      | -   Ch. 7-8 Problems TBD                                                                                                                                                             |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  | -   Ch. 8 Conditional Manatees                                                                                                                  |                                                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
| 4/26/2024                                        | -   Ch. 9 MCMC                                                                                                                                  | -   Ch. 9 Problems                                                                                                                                                                   |                 |
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
|                                                  |                                                                                                                                                 | -   Wrap-up and Planning                                                                                                                                                             |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
|                                                  |                                                                                                                                                 |                                                                                                                                                                                      |                 |
+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
